meta:  
  CSBUVB2hHirtTaq_GATATCGA_S1:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False    
  CSBUVC2hHirtTaq_AGCTCGCT_S2:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False    
  DDB2UVB2hHirtTaq_GTGTCGGA_S3:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False   
  DDB2UVC2hHirtTaq_TCCGCTAA_S4:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False  
  NHF1UVB2hHirtTaq_ACACTAAG_S5:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False 
  NHF1UVC2hHirtTaq_CTTATCGG_S6:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False  
  R124hBrdU100_ATGAGGCC_S7:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False
  R124hBrdU200_ACTAAGAT_S8:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False  
  R124hBrdU50_GCAGAATT_S9:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False   
  R224hBrdU20_TTGGACTC_S10:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False    
  NDDB2CPD2h_AGCGCTAG_S10:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False  
  NHF1UV12mCPD_GCAATGCA_S11:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False  
  R2G0HU64_CATAGAGT_S11:
    method: "XR"
    layout: "single"
    # product: "64pp"
    simulation:
      enabled: False    
  NDDB2CPD30m_GTGTCGGA_S11:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False 
  NHF1UV2hCPD_CTTATCGG_S12:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False  
  R2G0HUCPD_TCTCTACT_S12:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False  
  NDDB2CPD4h_GATATCGA_S12:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False  
  NHF1CPD10m_CTTATCGG_S13: 
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False    
  NHF1Cisp2hKappa_AGCTCGCT_S13:
    method: "XR"
    layout: "single"
    product: "Cisplatin"
    simulation:
      enabled: False   
  R2G0noHU64_ACAGGCGC_S13:
    method: "XR"
    layout: "single"
    # product: "64pp"
    simulation:
      enabled: False   
  NHF1UV4hCPD_TCCGCTAA_S13:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False
  R2G0noHUCPD_TGCGAGAC_S14:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False    
  NHF1Cisp2hQ5_TATGAGTA_S14:
    method: "XR"
    layout: "single"
    product: "Cisplatin"
    simulation:
      enabled: False 
  NHF1CPD2h_GATCTATC_S14:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False 
  NHF1UV8hCPD_GATCTATC_S14:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False   
  R2mixHU64_GCAATGCA_S15:
    method: "XR"
    layout: "single"
    simulation:
      enabled: False     
  NHF1Cisp2hTaq_AGCGCTAG_S15:
    method: "XR"
    layout: "single"
    product: "Cisplatin"
    simulation:
      enabled: False   
  NHF1CPD30m_TCCGCTAA_S15:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False  
  R2mixHUCPD_CCAAGTCT_S16:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False  
  NHF1CPD4h_AGCTCGCT_S16:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False   
  NHF1UV2h64Kappa_TCCGCTAA_S16:
    method: "XR"
    layout: "single"
    product: "64pp"
    simulation:
      enabled: False  
  R2mixnoHU64_ATGGCATG_S17:
    method: "XR"
    layout: "single"
    # product: "64pp"
    simulation:
      enabled: False  
  NHF1UV2h64Q5_GATATCGA_S17:
    method: "XR"
    layout: "single"
    product: "64pp"
    simulation:
      enabled: False    
  NHF1CPD8h_ACACTAAG_S17:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False   
  NHF1UV2h64Taq_ACACTAAG_S18:
    method: "XR"
    layout: "single"
    product: "64pp"
    simulation:
      enabled: False    
  R2mixnoHUCPD_CTCTCGTC_S18:
    method: "XR"
    layout: "single"
    # product: "CPD"
    simulation:
      enabled: False  
  XPCUVB2hHirtTaq_AGCGCTAG_S19:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False   
  NHF1UV2hCPDKappa_GATCTATC_S19:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False     
  XPCUVC2hHirtTaq_GATCTATC_S20:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False    
  NHF1UV2hCPDQ5_CGCAGACG_S20:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False      
  NHF1UV2hCPDTaq_GTGTCGGA_S21:
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False    

genome:
  build: "hg38"
  link: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/GRCh38.p14.genome.fa.gz"
  