
sample: 
  - "HDA64A1_ATCACG"
  - "HDA64B19_GTGAAA"
  - "HDACA6_GCCAAT"
  - "HDACB23_GAGTGG"
  - "HDE64A4_TGACCA"
  - "HDE64B20_GTGGCC"
  - "HDECA10_TAGCTT"
  - "HDECB25_ACTGAT"
  - "HDL64A5_ACAGTG"
  - "HDL64B22_CGTACG"
  - "HDLCA12_CTTGTA"
  - "HDLCB27_ATTCCT"
  - "NT4H1-CT5H2-HelaD1-5R2h2_combined"
  - "XT4H1-CT5H2-HelaD3-5R2h2_combined"
  - "R19029847-HD2TCD4-HelaD1-5R2h1_combined"
  - "R19029847-HD2TCD4-HelaD3-5R2h1_combined"

damage_type:
  - "64"
  - "64"
  - "CPD"
  - "CPD"
  - "64"
  - "64"
  - "CPD"
  - "CPD"
  - "64"
  - "64"
  - "CPD"
  - "CPD"
  - "CPD"
  - "CPD"
  - "CPD"
  - "CPD"

input:
  exist: True
  files:
    - "R19040024-HelainputD-Hl0h20JID"
    - "R19040024-HelainputD-Hl15R2hID"
    - "R19040024-HelainputD-Hl35R2hID"  
  sample: 
    - "0-3"
    - "4-7, 12, 14"
    - "8-11, 13, 15"

srr: 
  enabled: False
  codes:
    - "SRR3623532"

# Genome parameters 

genome_download: False

bowtie2_build: False

build: "hg19"

species: "homo_sapiens"

datatype: "dna"

release: "102"

#######

filter: "'^chr([1-9]|1[0-9]|2[0-2]|X)'"