meta: 
  test_xr_single_cpd_sim_input_paired:
    srr_id: "" 
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: True
      input: 
        name: "input_data"
        layout: "paired"
  test_xr_single_cpd_sim_input_single:
    srr_id: "" 
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: True
      input: 
        name: "input_data"
        layout: "single"
  test_xr_single_cpd_sim:
    srr_id: "" 
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: True
  test_xr_single_cpd:
    srr_id: "" 
    method: "XR"
    layout: "single"
    product: "CPD"
    simulation:
      enabled: False
  # test_ds_paired_cpd_sim_input_paired:
  #   srr_id: "" 
  #   method: "DS"
  #   layout: "paired"
  #   product: "CPD"
  #   simulation:
  #     enabled: True
  #     input: 
  #       name: "input_data"
  #       layout: "paired"
  # test_ds_paired_cpd_sim_input_single:
  #   srr_id: "" 
  #   method: "DS"
  #   layout: "paired"
  #   product: "CPD"
  #   simulation:
  #     enabled: True
  #     input: 
  #       name: "input_data"
  #       layout: "single"
  # test_ds_paired_cpd_sim:
  #   srr_id: "" 
  #   method: "DS"
  #   layout: "paired"
  #   product: "CPD"
  #   simulation:
  #     enabled: True
  # test_ds_paired_cpd:
  #   srr_id: "" 
  #   method: "DS"
  #   layout: "paired"
  #   product: "CPD"
  #   simulation:
  #     enabled: False

genome:
  build: "hg38"
  link: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_48/GRCh38.p14.genome.fa.gz"
  